# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dogs' do
  pod 'SwiftLint'
	pod 'Kingfisher', '~> 7.0'
	
  use_frameworks!

  # Pods for Dogs

  target 'DogsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DogsUITests' do
    # Pods for testing
  end

end
